# Generated by Django 5.2.7 on 2025-11-24 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': 'Muestra', 'verbose_name_plural': 'Muestras'},
        ),
        migrations.RemoveField(
            model_name='sample',
            name='collection_date',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sample_id',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sample_type',
        ),
        migrations.AddField(
            model_name='sample',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='secuenciacion/', verbose_name='Archivo de Secuenciación'),
        ),
        migrations.AddField(
            model_name='sample',
            name='enfermedad_paciente',
            field=models.CharField(default='Desconocida', max_length=200, verbose_name='Enfermedad del Paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='fecha_muestreo',
            field=models.DateField(default=None, verbose_name='Fecha de Muestreo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='fecha_secuenciacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Secuenciación'),
        ),
        migrations.AddField(
            model_name='sample',
            name='longitud',
            field=models.IntegerField(blank=True, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='sample',
            name='lugar_muestreo',
            field=models.CharField(default='Desconocido', max_length=200, verbose_name='Lugar de Muestreo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='muestra_id',
            field=models.CharField(default='-', max_length=100, verbose_name='ID de Muestra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='sample',
            name='plataforma',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plataforma'),
        ),
        migrations.AddField(
            model_name='sample',
            name='secuenciacion',
            field=models.BooleanField(default=False, verbose_name='¿Secuenciación?'),
        ),
        migrations.AddField(
            model_name='sample',
            name='tipo_muestra',
            field=models.CharField(default='Desconocido', max_length=100, verbose_name='Tipo de Muestra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
