# Generated by Django 5.2.7 on 2025-11-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_alter_sample_options_remove_sample_collection_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='longitud',
            field=models.IntegerField(blank=True, null=True, verbose_name='Longitud (bases)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='lugar_muestreo',
            field=models.CharField(max_length=200, verbose_name='Lugar de Muestreo (Ciudad, Estado)'),
        ),
    ]
